//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.15 at 12:13:52 AM IST 
//


package service.bank.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Payee complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="payee_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="payee_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payee_account_number" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="customer_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payee", propOrder = {
    "payeeId",
    "payeeName",
    "payeeAccountNumber",
    "customerId"
})
public class Payee {

    @XmlElement(name = "payee_id")
    protected int payeeId;
    @XmlElement(name = "payee_name", required = true)
    protected String payeeName;
    @XmlElement(name = "payee_account_number")
    protected long payeeAccountNumber;
    @XmlElement(name = "customer_id")
    protected int customerId;

    /**
     * Gets the value of the payeeId property.
     * 
     */
    public int getPayeeId() {
        return payeeId;
    }

    /**
     * Sets the value of the payeeId property.
     * 
     */
    public void setPayeeId(int value) {
        this.payeeId = value;
    }

    /**
     * Gets the value of the payeeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * Sets the value of the payeeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeName(String value) {
        this.payeeName = value;
    }

    /**
     * Gets the value of the payeeAccountNumber property.
     * 
     */
    public long getPayeeAccountNumber() {
        return payeeAccountNumber;
    }

    /**
     * Sets the value of the payeeAccountNumber property.
     * 
     */
    public void setPayeeAccountNumber(long value) {
        this.payeeAccountNumber = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     */
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     */
    public void setCustomerId(int value) {
        this.customerId = value;
    }

}
